services:
  php:
    build: infra/docker/php
    container_name: php_xdebug
    hostname: php_xdebug
    ports:
      - "8080:8080"
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    environment:
      XDEBUG_CONFIG: "remote_host=host.docker.internal"
    entrypoint: php -S 0.0.0.0:8080
